# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ultra Pixelmon Launcher"

[ejs.landing]
mediaGitHubURL = "https://ultra-pixelmon.xyz/"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/ultrapixelmon/"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/nEG8fpX"

[ejs.settings]
sourceGithubLink = "https://ultra-pixelmon.xyz/"
supportLink = "https://ultra-pixelmon.xyz/"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ULTRA-PIXELMON 1.20.2"
welcomeDescription = "Découvrez notre serveur MMORPG moddé basé sur l'univers de Minecraft et Pixelmon. Plus de 900 Pokémon à capturer, un hôtel des ventes, une chasse aux Pokémon PixelHunt et des combats PvP Showdown. Explorez un vaste safari au début de votre aventure, accomplissez des quêtes et remportez des récompenses quotidiennes. Revivez vos meilleurs souvenirs Pokémon au sein d'une communauté multijoueur dynamique."
welcomeDescCTA = ""
